dataset_config:
  masked_vcr:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: true
    use_features: false
    annotations:
      train:
      - vcr/defaults/vcr1annots/train.jsonl
      val:
      - vcr/defaults/vcr1annots/val.jsonl
      test:
      - vcr/defaults/vcr1annots/test.jsonl
    max_features: 100
    two_sentence: true
    two_sentence_probability: -0.1
    false_caption: true
    false_caption_probability: 0.5
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 128
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.90
      transformer_bbox_processor:
          type: transformer_bbox
          params:
            bbox_key: bbox
            image_width_key: image_width
            image_height_key: image_height
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
